// react-demo/src/App.js
import React from 'react';
import { defineCustomElements } from 'stencil-demo/loader';
// import { MyCard } from './components/stencil-generated';

defineCustomElements();

function App() {
  return (
    <div>
      <my-card title="Hello World" content="This is a card component" />
    </div>
  );
}

export default App;

// angular-demo/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { DIRECTIVES } from './stencil-generated';
import { defineCustomElements } from '../../../stencil-demo/loader';

defineCustomElements();

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, ...DIRECTIVES],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss',
})
export class AppComponent {
  title = 'angular-demo';
}

<div>hello</div>
<my-card title="Angular Card" content="This is a card Used in a Angular Project"></my-card>
